//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csFiddle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public System.Guid id { get; set; }
        public int version { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> parentId { get; set; }
        public string userCode { get; set; }
        public bool latest { get; set; }
    }
}
